apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scale-grafana
  namespace: monitoring
rules:
  - apiGroups: ["apps"]
    resources:
      - deployments
      - deployments/scale
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scale-grafana
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: default
    namespace: actions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scale-grafana
