apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- grafana.yaml
- grafana-dashboards-configmap.yaml
- promrule-hello.yaml
- promrule.yaml
- servicemonitor-hello.yaml
- servicemonitor.yaml
patchesStrategicMerge:
- grafana-dashboards-patch.yaml
