apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: metrics-echo
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/hirakuarai/metrics-echo:dev
        env: [{ name: TARGET, value: "vpm-mini" }]
